### ISSUE TITLE
[bug] Exception handler 고장

### ISSUE THREAD

**Issue by Camof1ow** [Camof1ow/itMonsters#10]
## 설명
현재 BAD_REQUEST의 Exception이 
모두 401 Unauthorized로 출력되는 버그가 있습니다.
이 부분 개선이 필요합니다.

## 진행상황
- [x] 원인 확인 중
- [x] 코드 수정 중
- [x] api 테스트
- [x] 완료

## 기타사항

<br><br>

**Comment by oneqrhee** [comment]
어떤 api 요청시 발생하는지 알수 있을까요?

**Comment by oneqrhee** [comment]
WebSecurityConfig 파일 152번째 줄 FilterSkipMatcher 에 skipPathList를 적용하는 부분에서 processingPath 를 "/**"로 설정해놔 모든 요청이 jwt필터를 거치게 되는것 같습니다. skipPathList에 "/api/members/login"을 추가하고 processingPath를 적절히 변경하면 해결될 것으로 생각됩니다.

**Comment by Camof1ow** [comment]
> 

일단 Security 설정에서 errorHandling이 안되는 것 확인했습니다.
찾아보며 테스트해본 결과 JwtAuthFilter 42번째줄 try 구문에서 IOexception 으로 토큰이 없을 때 보내는 Error가 어째서인지
모든 IOexception 처리 결과로 나가게 설정되었던 것으로 확인했습니다.
수정하고 다시 테스트 해보는 대로 Issue 닫겠습니다. 고생하셨습니다.

**Comment by Camof1ow** [comment]
우선은 MemberService 기능마다 IOexception이 필요한 부분에 추가해주는 방법으로 해결했습니다.
코드 리팩토링 후에 푸시해놓겠습니다. null체크를 통해 검증이 필요하고 이에 따른 에러코드를 출력하길 원하시면 
Service 검증 메소드 참고 부탁드리겠습니다.
