### ISSUE TITLE
[기능개발] Quest Response 변경, Refactoring

### ISSUE THREAD

**Issue by oneqrhee** [Camof1ow/itMonsters#11]
## 설명
Quest Response 통일
반복되는 코드 메서드 생성

## 진행상황
- [x] 사전준비
- [x] 착수
- [x] api 테스트
- [x] 완료

## 기타사항

<br><br>

**Comment by oneqrhee** [comment]
완료 !

**Comment by Camof1ow** [comment]
👏👏👏👏
