### ISSUE TITLE
[기능개발] 자동배포 시작

### ISSUE THREAD

**Issue by Camof1ow** [Camof1ow/itMonsters#33]
## 설명
자동배포 시작하였습니다.
프로젝트명 변경에 다른 경로명을 변경하였습니다.

수정된 내용들 dev branch 반영하였으니
pull 해가셔서 확인하시고 수정 필요하신 부분은
수정하셔 PR 해주시면 됩니다.

특이사항은 아래 comment로 남겨주시면 확인하겠습니다.

서버 주소 단톡방으로 남기겠습니다.

## 진행상황
- [x] 사전준비
- [x] 착수
- [x] api 테스트
- [x] 완료

## 기타사항
진행사항에 대해 적어주세요

<br><br>

**Comment by kimjinmoo91** [comment]
수고하셨습니다. !
